all: download dependency build

[no-cd]
download:
	mkdir -p ros2_rolling_system_test_ws/src
	cd ros2_rolling_system_test_ws/src && \
		git clone https://github.com/ros2/system_tests.git -b rolling && \
		git clone https://github.com/ros2/rcl.git -b rolling && \
		git clone https://github.com/ros2/rclcpp.git -b rolling && \
		git clone https://github.com/ros2/rclpy.git -b rolling && \
		git clone https://github.com/ros2/rclc.git -b rolling
	## Switch to certain commit
	#cd ros2_rolling_system_test_ws/src/system_tests && git checkout f09a98a46f84ee6e07ead2626fc2ed63bf429dd7
	#cd ros2_rolling_system_test_ws/src/rcl && git checkout 673c558fa7ff5434a489857df75064ebdb0ee5a8
	#cd ros2_rolling_system_test_ws/src/rclcpp && git checkout a0a2a067d84fd6a38ab4f71b691d51ca5aa97ba5
	#cd ros2_rolling_system_test_ws/src/rclpy && git checkout ba72a017a9a1f8d2a92e615cafed318d99f7576f	
	#cd ros2_rolling_system_test_ws/src/rclc && git checkout 6f0a9edb3cf30df0368d3abbad2fa66149e5cc65

[no-cd]
dependency:
	rosdep update
	cd ros2_rolling_system_test_ws && rosdep install --from-paths src --ignore-src -y

[no-cd]
build:
	cd ros2_rolling_system_test_ws && colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DSKIP_MULTI_RMW_TESTS=On

[no-cd]
test:
	cd ros2_rolling_system_test_ws && colcon test
	python3 common/collect_test_result.py ros2_rolling_system_test_ws

[no-cd]
clean:
	rm -rf ros2_rolling_system_test_ws
