all: download dependency build

[no-cd]
download:
	mkdir -p ros2_rolling_src_ws/src
	cd ros2_rolling_src_ws && \
		wget https://raw.githubusercontent.com/Yadunund/ros2/8792a97457822a5f3dad6503bfb2b0712ef4b539/ros2.repos && \
		vcs import src < ros2.repos && \
		vcs pull src

[no-cd]
dependency:
	sudo rm -rf /etc/ros/rosdep/sources.list.d/20-default.list
	sudo rosdep init
	sudo apt update
	rosdep update
	cd ros2_rolling_src_ws && rosdep install --from-paths src --ignore-src -y --skip-keys "fastcdr rti-connext-dds-6.0.1 urdfdom_headers"

[no-cd]
build:
	cd ros2_rolling_src_ws && colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

[no-cd]
test:
	cd ros2_rolling_src_ws && colcon test
	python3 common/collect_test_result.py ros2_rolling_src_test_ws

[no-cd]
clean:
	rm -rf ros2_rolling_src_ws
