all: download dependency build

[no-cd]
download:
	mkdir -p ros2_rolling_simple_examples_ws/src
	cd ros2_rolling_simple_examples_ws/src && git clone https://github.com/evshary/ros2-simple-examples.git

[no-cd]
dependency:
	rosdep update
	cd ros2_rolling_simple_examples_ws && rosdep install --from-paths src --ignore-src -y

[no-cd]
build:
	cd ros2_rolling_simple_examples_ws && colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

[no-cd]
debug:
	cd ros2_rolling_simple_examples_ws && \
		colcon build --symlink-install \
					 --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
								  -DCMAKE_BUILD_TYPE=Debug
	echo "Create .env file to be used in debug mode"
	bash -c "source /opt/ros/rolling/setup.bash; printenv | grep ros > .env"

[no-cd]
debug_ubsan:
	cd ros2_rolling_simple_examples_ws && \
		colcon build --symlink-install \
					 --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
								  -DCMAKE_BUILD_TYPE=Debug \
								  -DCMAKE_CXX_FLAGS="-fsanitize=undefined"

[no-cd]
debug_asan:
	cd ros2_rolling_simple_examples_ws && \
		colcon build --symlink-install \
					 --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
								  -DCMAKE_BUILD_TYPE=Debug \
								  -DCMAKE_CXX_FLAGS="-fsanitize=address"

[no-cd]
clean:
	rm -rf ros2_rolling_simple_examples_ws
