all: download dependency build

[no-cd]
download:
	mkdir -p ros2_rolling_simple_performance_ws/src
	cd ros2_rolling_simple_performance_ws/src && git clone https://github.com/ZettaScaleLabs/ros2-simple-performance.git

[no-cd]
dependency:
	rosdep update
	cd ros2_rolling_simple_performance_ws && rosdep install --from-paths src --ignore-src -y

[no-cd]
build:
	cd ros2_rolling_simple_performance_ws && colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

[no-cd]
clean:
	rm -rf ros2_rolling_simple_performance_ws
