all: download dependency build

[no-cd]
download:
	mkdir -p src
	cd src && git clone https://github.com/ZettaScaleLabs/rmw_zenoh.git -b dev/1.0.0

[no-cd]
dependency:
	rosdep update
	rosdep install --from-paths src --ignore-src --rosdistro jazzy -y

[no-cd]
build:
	colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

[no-cd]
clean:
	rm -rf build install log
