all: download dependency build

[no-cd]
download:
	mkdir -p ros2_jazzy_nav2_ws/src
	cd ros2_jazzy_nav2_ws/src && \
		git clone https://github.com/ros-navigation/navigation2.git -b jazzy

[no-cd]
dependency:
	sudo rm -rf /etc/ros/rosdep/sources.list.d/20-default.list
	sudo rosdep init
	sudo apt update
	rosdep update
	cd ros2_jazzy_nav2_ws && rosdep install --from-paths src --ignore-src --rosdistro jazzy -y

[no-cd]
build:
	cd ros2_jazzy_nav2_ws && colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

[no-cd]
clean:
	rm -rf ros2_jazzy_nav2_ws
