all: download dependency build

[no-cd]
download:
	mkdir -p ros2_rolling_nav2_ws/src
	cd ros2_rolling_nav2_ws/src && \
		git clone https://github.com/ros-navigation/navigation2.git -b main && \
		git clone https://github.com/ros2/common_interfaces.git

[no-cd]
dependency:
	sudo rm -rf /etc/ros/rosdep/sources.list.d/20-default.list
	sudo rosdep init
	sudo apt update
	rosdep update
	cd ros2_rolling_nav2_ws && rosdep install --from-paths src --ignore-src --rosdistro rolling -y -r

[no-cd]
build:
	cd ros2_rolling_nav2_ws && colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

[no-cd]
test:
	cd ros2_rolling_nav2_ws && colcon test
	python3 common/collect_test_result.py ros2_rolling_nav2_ws

[no-cd]
clean:
	rm -rf ros2_rolling_nav2_ws
