all: download dependency build

[no-cd]
download:
	mkdir -p ros2_rolling_cyclonedds_ws/src
	cd ros2_rolling_cyclonedds_ws/src && \
		git clone https://github.com/eclipse-cyclonedds/cyclonedds.git -b master

[no-cd]
dependency:
	rosdep update
	cd ros2_rolling_cyclonedds_ws && rosdep install --from-paths src --ignore-src -y

[no-cd]
build:
	cd ros2_rolling_cyclonedds_ws && colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug

[no-cd]
clean:
	rm -rf ros2_rolling_cyclonedds_ws
